[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.21"
fs_permissions = [
    { access = "read", path = "./script/input/"},
    { access = "read", path = "./out/"},
    { access = "read-write", path = "./script/output/"}
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
sepolia = { key ="${ETHERSCAN_MAINNET_KEY}", chain = 11155111 }
arbitrum_sepolia = { key = "${ETHERSCAN_ARBITRUM_KEY}", chain = 421614, url = "https://api-sepolia.arbiscan.io/api" }